Zeek dns.log
ocsf/examples pull request #33
Opened 2023-07-13 17:53 UTC by rekidderjr

Looking for review of proposed Zeek dns.log mapping

2023-07-13 19:02 UTC, floydtree requested changes
Can you also add a transformed/OCSF version of the zeek event that you have?

2023-07-13 19:02 UTC, floydtree commented on Network Activity/DNS Activity/Zeek/dns_log/README.md
> +|'TTLs'|unmapped'|
can be mapped to `dns_answer.ttl`

2023-07-13 20:03 UTC, rkidderaws commented on Network Activity/DNS Activity/Zeek/dns_log/README.md
> +|'time'|'time'|
Sorry I miss pasted both raw and ocsf with the same values.  Whoops! Fixing now

2023-07-14 13:37 UTC, rkidderaws commented on Network Activity/DNS Activity/Zeek/dns_log/README.md
> +|'TTLs'|unmapped'|
Corrected ttl mapping as requested.

2023-07-14 14:51 UTC, closed without merging