Initial commit of SiLK Network Flow Record
ocsf/examples pull request #36
Opened 2023-07-27 14:01 UTC by sei-mthomas

2023-07-27 16:53 UTC, floydtree requested changes

2023-07-27 16:53 UTC, floydtree commented on Network Activity/Network Activity/CERT-NetSA at CMU-SEI/SiLK Network Flow Data/SiLK_OCSF_Mapping_v1.1.xlsx
you can remove this file, no need for it since you are covering the mapping the readme.md file

2023-07-27 18:14 UTC, sei-mthomas commented on Network Activity/Network Activity/CERT-NetSA at CMU-SEI/SiLK Network Flow Data/SiLK_OCSF_Mapping_v1.1.xlsx
Thanks. Removed the file.

2023-08-08 15:12 UTC, mr-splunk approved these changes

2023-08-14 13:59 UTC, Aniak5 approved these changes

2023-08-14 13:59 UTC, merged