AWS update folder structure and mappings to 1.1.0
ocsf/examples pull request #55
Opened 2024-03-16 04:25 UTC by zschmerber

Adding update for 1.1.0 folders and AWS 1.1.0 OCSF mappings

2024-03-19 18:03 UTC, floydtree requested changes

2024-03-19 18:03 UTC, floydtree commented on mappings/bloblang/AWS/CloudTrail/samples/account_change.ocsf
Are you removing the transformed files intentionally? I think we should maintain .raw and .ocsf for samples for each version of mapping that is published. Similar to how we have the markdown mappings for AWS - https://github.com/ocsf/examples/tree/main/mappings/markdown/AWS

2024-03-19 18:11 UTC, zschmerber commented on mappings/bloblang/AWS/CloudTrail/samples/account_change.ocsf
Yes, the thought was the person can use the Blobl to make a transformed file so why include it?

2024-03-19 18:13 UTC, zschmerber commented on mappings/bloblang/AWS/CloudTrail/samples/account_change.ocsf
I can add them back if you think it would be helpful

2024-03-19 18:34 UTC, floydtree commented on mappings/bloblang/AWS/CloudTrail/samples/account_change.ocsf
To help add context to the mappings themselves. Seeing a transformed record along with a raw record, helps in that regard. It helps in understanding the mappings as well i.e. x operation leads to such an output et al

2024-03-19 18:36 UTC, zschmerber commented on mappings/bloblang/AWS/CloudTrail/samples/account_change.ocsf
Ok I will Update the PR thanks for the review.

2024-03-28 19:16 UTC, Aniak5 reviewed
I love the restructuring, it makes a lot of sense. `Account Change` is misspelled :D but otherwise looks great!

2024-03-29 19:31 UTC, floydtree requested changes

2024-03-29 19:31 UTC, floydtree commented on mappings/bloblang/AWS/route53/route53.yml
Going back to the earlier comments (I see you added the structure and samples to CT, thank you!), r53 doesn't seem to have transformed samples. I think if we are adding samples, we should both raw and transformed, don't see only raw samples being as helpful to users.

2024-04-02 13:17 UTC, floydtree approved these changes

2024-04-05 19:49 UTC, Aniak5 approved these changes

2024-04-05 19:52 UTC, mikeradka approved these changes
The version folder helps, nice work

2024-04-05 19:52 UTC, merged