Update ssl with field mappings and example logs
ocsf/examples pull request #89
Opened 2024-11-08 02:37 UTC by JW-Corelight

2024-12-03 18:01 UTC, irakledibm approved these changes

2025-01-09 20:16 UTC, Aniak5 commented on mappings/markdown/Zeek/v1.3.0/ssl_log/samples/ssl_log.raw
> +  "validation_status": "certificate has expired",
I feel like we should have field to represent the `validation_status`

2025-01-10 04:48 UTC, zschmerber approved these changes

2025-01-10 17:41 UTC, irakledibm requested changes
Examples still have incorrect timestamp formatting.

2025-01-10 17:49 UTC, Aniak5 approved these changes

2025-01-10 17:53 UTC, mikeradka commented
Piggybacking on Irakle's note about the timestamps in the ocsf output example, here are the errors I encountered with the v2 validator:

```json
"errors": [
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.alert\" value has wrong type; expected integer_t, got string_t.",
      "value": "certificate_unknown",
      "attribute": "alert",
      "value_type": "string_t",
      "attribute_path": "tls.alert",
      "expected_type": "integer_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"tls.certificate.fingerprints\" is missing.",
      "attribute": "fingerprints",
      "attribute_path": "tls.certificate.fingerprints"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"tls.certificate.serial_number\" is missing.",
      "attribute": "serial_number",
      "attribute_path": "tls.certificate.serial_number"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.ja3_hash\" value has wrong type; expected fingerprint (object), got string_t.",
      "value": "f0bb8fb38d017e359d2692a270974136",
      "attribute": "ja3_hash",
      "value_type": "string_t",
      "attribute_path": "tls.ja3_hash",
      "expected_type": "fingerprint (object)"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.ja3s_hash\" value has wrong type; expected fingerprint (object), got string_t.",
      "value": "00447ab319e9d94ba2b4c1248e155917",
      "attribute": "ja3s_hash",
      "value_type": "string_t",
      "attribute_path": "tls.ja3s_hash",
      "expected_type": "fingerprint (object)"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"start_time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:30.489454Z",
      "attribute": "start_time",
      "value_type": "string_t",
      "attribute_path": "start_time",
      "expected_type": "timestamp_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"type_uid\" is missing.",
      "attribute": "type_uid",
      "attribute_path": "type_uid"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"metadata.logged_time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:36.459547Z",
      "attribute": "logged_time",
      "value_type": "string_t",
      "attribute_path": "metadata.logged_time",
      "expected_type": "timestamp_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"metadata.loggers[0].product.vendor_name\" is missing.",
      "attribute": "vendor_name",
      "attribute_path": "metadata.loggers[0].product.vendor_name"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:30.489454Z",
      "attribute": "time",
      "value_type": "string_t",
      "attribute_path": "time",
      "expected_type": "timestamp_t"
    }
  ],
  "error_count": 10,
```

2025-01-10 17:54 UTC, mikeradka requested changes
Piggybacking on Irakle's note about the timestamps in the ocsf output example, here are the errors I encountered with the v2 validator:

```json
"errors": [
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.alert\" value has wrong type; expected integer_t, got string_t.",
      "value": "certificate_unknown",
      "attribute": "alert",
      "value_type": "string_t",
      "attribute_path": "tls.alert",
      "expected_type": "integer_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"tls.certificate.fingerprints\" is missing.",
      "attribute": "fingerprints",
      "attribute_path": "tls.certificate.fingerprints"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"tls.certificate.serial_number\" is missing.",
      "attribute": "serial_number",
      "attribute_path": "tls.certificate.serial_number"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.ja3_hash\" value has wrong type; expected fingerprint (object), got string_t.",
      "value": "f0bb8fb38d017e359d2692a270974136",
      "attribute": "ja3_hash",
      "value_type": "string_t",
      "attribute_path": "tls.ja3_hash",
      "expected_type": "fingerprint (object)"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"tls.ja3s_hash\" value has wrong type; expected fingerprint (object), got string_t.",
      "value": "00447ab319e9d94ba2b4c1248e155917",
      "attribute": "ja3s_hash",
      "value_type": "string_t",
      "attribute_path": "tls.ja3s_hash",
      "expected_type": "fingerprint (object)"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"start_time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:30.489454Z",
      "attribute": "start_time",
      "value_type": "string_t",
      "attribute_path": "start_time",
      "expected_type": "timestamp_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"type_uid\" is missing.",
      "attribute": "type_uid",
      "attribute_path": "type_uid"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"metadata.logged_time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:36.459547Z",
      "attribute": "logged_time",
      "value_type": "string_t",
      "attribute_path": "metadata.logged_time",
      "expected_type": "timestamp_t"
    },
    {
      "error": "attribute_required_missing",
      "message": "Required attribute \"metadata.loggers[0].product.vendor_name\" is missing.",
      "attribute": "vendor_name",
      "attribute_path": "metadata.loggers[0].product.vendor_name"
    },
    {
      "error": "attribute_wrong_type",
      "message": "Attribute \"time\" value has wrong type; expected timestamp_t (long_t), got string_t.",
      "value": "2024-10-18T13:57:30.489454Z",
      "attribute": "time",
      "value_type": "string_t",
      "attribute_path": "time",
      "expected_type": "timestamp_t"
    }
  ],
  "error_count": 10,
```

2025-01-10 19:23 UTC, JW-Corelight commented
> Examples still have incorrect timestamp formatting.

You're right, Irankle.. great catch.  Thank you

2025-01-14 17:07 UTC, irakledibm approved these changes

2025-01-14 20:31 UTC, mikeradka approved these changes

2025-01-14 21:50 UTC, Aniak5 approved these changes

2025-01-14 21:50 UTC, merged