Add rdp with field mapping and example logs
ocsf/examples pull request #92
Opened 2024-11-08 02:48 UTC by JW-Corelight

2024-12-03 18:02 UTC, irakledibm approved these changes

2024-12-12 03:39 UTC, irakledibm requested changes
time, start_time and logged_time are of type timestamp_t, which is Long data type. An example is showing this format: "logged_time": "2024-10-16T04:18:12.066275Z", corresponding to datetime_t, which is incorrect. Value have to be converted to a numeric representation.

2025-01-09 19:22 UTC, Aniak5 commented on mappings/markdown/Zeek/v1.3.0/rdp_log/README.md
> +| `observables[].value`          | `rdfp_string`     | A fingerprint which represents an RDP client.                                           | In an object where `observables[].type_id` = "99", <br
Should this be `type_id=30` as well given that this is a fingerprint?

2025-01-09 19:29 UTC, Aniak5 commented on mappings/markdown/Zeek/v1.3.0/rdp_log/README.md
> +| `observables[].value`          | `keyboard_layout` | Keyboard layout (language) of the client machine.                                       | In an object where `observables[].type_id` = "99", <br
We have a `keyboard_info` object which contains this attribute. Likely we should add this to the RDP event class

2025-01-10 04:47 UTC, zschmerber approved these changes

2025-01-10 17:38 UTC, irakledibm approved these changes

2025-01-10 17:47 UTC, mikeradka approved these changes
Looks great

2025-01-10 17:47 UTC, merged