Add smtp with field mapping and example logs
ocsf/examples pull request #93
Opened 2024-11-08 02:51 UTC by JW-Corelight

2024-12-03 18:04 UTC, irakledibm submitted a review, later dismissed

2024-12-12 03:54 UTC, irakledibm requested changes
time, start_time and logged_time are of type timestamp_t, which is Long data type. An example is showing this format: "logged_time": "2024-10-16T04:18:12.066275Z", corresponding to datetime_t, which is incorrect. Value have to be converted to a numeric representation.

2024-12-16 21:08 UTC, JW-Corelight commented
I believe I have resolved this and other discrepancies just as they were resolved in the SSH PR

2024-12-17 17:07 UTC, JW-Corelight commented
I noticed when i validated the mapping that it looks like `email.to[]` in OCSF v1.3.0 may incorrectly type this as only the email address.

2025-01-06 20:27 UTC, JW-Corelight commented
> time, start_time and logged_time are of type timestamp_t, which is Long data type. An example is showing this format: "logged_time": "2024-10-16T04:18:12.066275Z", corresponding to datetime_t, which is incorrect. Value have to be converted to a numeric representation.


I believe I have resolved this and other discrepancies just as they were resolved in the SSH PR

2025-01-09 19:29 UTC, floydtree approved these changes

2025-01-09 19:47 UTC, zschmerber approved these changes

2025-01-09 19:48 UTC, Aniak5 approved these changes

2025-01-09 19:48 UTC, merged